- fullName: NCHU AI Learning Advisor
  shortName: ALA
  image: /assets/images/ALA.png
  context: 基於 Claude API + MCP 協議，整合中興大學課程、圖書館和跨領域課程工具的查詢工具。
  tags: [Claude, MCP]
  authors: [{name: "Hsing-Ping Liang,"}, {name: 范耀中, link:\#}]
  links: [
    {name: Demo, style: btn-primary, href: https://eduxplore.nlpnchu.org/}
  ]

- fullName: 神農TAIDE
  shortName: demetergpt
  image: /assets/images/lab-logo.png
  context: 基於台灣語言模型TAIDE的先進RAG，用於回答農業相關問題。
  tags: [ChatGPT, pyserini, BM25, Qusetion Answering]
  authors: [{name: 范耀中, link:\#}]
  links: [
    {name: Demo, style: btn-primary, href: https://demetergptv2.nlpnchu.org/}
  ]

  
