- fullName: Cloze Distractor Generator
  shortName: CDGP
  image: /assets/images/CDGP.png
  context: 基於語言預訓練模型之克漏字干擾選項自動生成，輸入文章並選擇挖空位置，即可自動生成其他干擾選項。
  tags: [Cloze, Distractor Generation, BERT]
  authors: [{name: Shang-Hsuan Chiang, link: https://github.com/AndyChiangSH}]
  links: [
    {name: Demo, style: btn-primary, href: https://cdgp-demo.nlpnchu.org/}
  ]
  gitRepo: AndyChiangSH/CDGP

- fullName: Querator AI
  shortName: Querator AI
  image: /assets/images/querator.png
  context: A powerful AI that understanding your articles and automatically generate questions for you.
  tags: [QG, BERT, Multi-Lang]
  authors: [{name: Ying-Hong Chan, link: https://github.com/Harry-Chan}]
  links: [
    {name: Paper, style: btn-success, href: https://aclanthology.org/D19-5821/},
    {name: Demo, style: btn-primary, href: https://classic.queratorai.com/}
  ]

- fullName: Nerual Question Group Generator
  shortName: NQGG
  image: /assets/images/qgg.png
  context: 閱讀理解題組生成；一篇文章，一個按鍵，立即生成。
  tags: [QGG, BART, GA, NL Learning]
  authors: [{name: Po-Chun Huang, link: https://github.com/p208p2002}]
  links: [
    {name: Demo, style: btn-primary, href: https://qgg-demo.nlpnchu.org}
  ]
  gitRepo: p208p2002/Neural-Question-Group-Generation

- fullName: Nerual Distractor Generator
  shortName: BDG
  image: /assets/images/lab-logo.png
  context: 閱讀理解多選題干擾選項生成，給文章，問題和答案生成干擾選項
  tags: [Distractor, Text Generation]
  authors: [{name: Eric Lam, link: https://github.com/voidful}]
  links: [
    {name: Demo, style: btn-primary, href: https://nlp2go.nlpnchu.org}
  ]
  gitRepo: voidful/BDG

- fullName: 犯罪人關係網路
  shortName: 犯罪人網路
  context: 使用截至2018年為止以前公開的判決書，製作犯罪人關係的視覺化圖譜
  tags: [犯罪人網路, 社群網路分析]
  authors: [{name: 姜立綱,link:\#}, {name: 郭溫蘋,link:\#}] 
  links: [
    {name: Demo, style: btn-primary, href: https://crime-network.nlpnchu.org/graph/}
  ]
  
- fullName: Misleading Inference Generation
  shortName: MIG
  image: /assets/images/lab-logo.png
  context: 基於強化學習之誤導推論生成，給一段句子，標記出想要生成誤導推論的原句，生成誤導推論
  tags: [BART, Text Generation, Reinforcement Learning]
  authors: [{name: 彭顯詠, link: https://github.com/seanbbear}]
  links: [
    {name: Demo, style: btn-primary, href: https://mig.nlpnchu.org/}
  ]

- fullName: 法律判決書相似檢索系統
  shortName: LSCBS
  image: /assets/images/lab-logo.png
  context: 此系統的主要目的為提供一般使用者輸入自己的刑事案件情境，系統即會回饋最相似案件情境的前N篇法律判決書。
  tags: [BERT]
  authors: [{name: 曹錫璋, link: https://github.com/an8282p}]
  links: [
    {name: Demo, style: btn-primary, href: https://lscbs.nlpnchu.org/LSCBS.html}
  ]
  
- fullName: Question Answering
  shortName: QA
  image: /assets/images/lab-logo.png
  context: 問答系統；給定一篇中英文文章和問句；系統會生成答案。
  tags: [BERT, SQuAD2.0, drcd, Qusetion Answering]
  authors: [{name: HankyStyle, link: https://github.com/HankyStyle}]
  links: [
    {name: Demo, style: btn-primary, href: https://qa.nlpnchu.org/}
  ]
