- fullName: TAIDE相似判決書檢索系統
  shortName: LAW
  image: /assets/images/lab-logo.png
  context: 此系統為一個準確又有效率的相似判決書檢索平台，適合法律專業人士及一般民眾使用。
  tags: [BERT]
  authors: [{name: 鄭宇辰, link:\#}, {name: 李彥吾,link:\#}]
  links: [
    {name: Demo, style: btn-primary, href: http://140.120.13.248:11304/}
  ]

- fullName: 神農TAIDE
  shortName: demetergpt
  image: /assets/images/lab-logo.png
  context: 基於台灣語言模型TAIDE的先進RAG，用於回答農業相關問題。
  tags: [ChatGPT, pyserini, BM25, Qusetion Answering]
  authors: [{name: 范耀中, link:\#}]
  links: [
    {name: Demo, style: btn-primary, href: https://demetergptv2.nlpnchu.org/}
  ]


- fullName: Cloze Distractor Generator
  shortName: CDGP
  image: /assets/images/CDGP.png
  context: 基於語言預訓練模型之克漏字干擾選項自動生成，輸入文章並選擇挖空位置，即可自動生成其他干擾選項。
  tags: [Cloze, Distractor Generation, BERT]
  authors: [{name: Shang-Hsuan Chiang, link: https://github.com/AndyChiangSH}]
  links: [
    {name: Demo, style: btn-primary, href: https://cdgp-demo.nlpnchu.org/}
  ]
  gitRepo: AndyChiangSH/CDGP

- fullName: Querator AI
  shortName: Querator AI
  image: /assets/images/querator.png
  context: A powerful AI that understanding your articles and automatically generate questions for you.
  tags: [QG, BERT, Multi-Lang]
  authors: [{name: Ying-Hong Chan, link: https://github.com/Harry-Chan}]
  links: [
    {name: Paper, style: btn-success, href: https://aclanthology.org/D19-5821/},
    {name: Demo, style: btn-primary, href: https://classic.queratorai.com/}
  ]

- fullName: 選擇題自動生成系統
  shortName: demetergpt
  image: /assets/images/lab-logo.png
  context: 三步驟，針對任意主題，生成選擇題考體。
  tags: [ChatGPT, pyserini, BM25, Qusetion Generation]
  authors: [{name: 賴信彰, link: https://github.com/s1072954}]
  links: [
    {name: Demo, style: btn-primary, href: https://mcq-demo.nlpnchu.org/}
  ]
  
