- fullName: NCHU AI Learning Advisor
  shortName: ALA
  image: /assets/images/ALA.png
  context: 基於 Claude API + MCP 協議，整合中興大學課程、圖書館和跨領域課程工具的查詢工具。
  tags: [Claude, MCP]
  authors: [{name: "Hsing-Ping Liang,"}, {name: 范耀中, link:\#}]
  links: [
    {name: Demo, style: btn-primary, href: https://eduxplore.nlpnchu.org/}
  ]

- fullName: 神農TAIDE
  shortName: demeteragent
  image: /assets/images/lab-logo.png
  context: 基於 Claude API 與 MCP 協議構建的多模態智慧農業代理，整合 AI 視覺辨識與農業專業知識，支援診斷、教學與決策輔助。
  tags: [Claude, MCP, Multimodal-Analysis]
  authors: [{name: 范耀中, link:\#}]
  links: [
    {name: Demo, style: btn-primary, href: https://demeteragent.nlpnchu.org/}
  ]

  
